In [1]:
import tensorflow as tf

/home/jasonhaven/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [13]:
tf.random_normal([2,3],mean=0,stddev=2)

<tf.Tensor 'random_normal_6:0' shape=(2, 3) dtype=float32>

In [14]:
weights=tf.Variable(tf.random_normal(shape=[2,3],stddev=2))

In [15]:
biases=tf.Variable(tf.zeros(shape=[3]))

In [26]:
#forward propogation

import tensorflow as tf

w1=tf.Variable(tf.random_normal(shape=[2,3],stddev=1,seed=1))
w2=tf.Variable(tf.random_normal(shape=[3,1],stddev=1,seed=1))

x=tf.constant([0.7,0.9],shape=[1,2])

a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

with tf.Session() as sess:
    sess.run(w1.initializer)
    sess.run(w2.initializer)
    print(sess.run(y))

[[3.957578]]


In [28]:
#forward propogation

import tensorflow as tf

w1=tf.Variable(tf.random_normal(shape=[2,3],stddev=1,seed=1))
w2=tf.Variable(tf.random_normal(shape=[3,1],stddev=1,seed=1))

x=tf.constant([0.7,0.9],shape=[1,2])

a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    print(sess.run(y))

[[3.957578]]


In [38]:
#forward propogation

import tensorflow as tf

w1=tf.Variable(tf.random_normal(shape=[2,3],stddev=1,seed=1))
w2=tf.Variable(tf.random_normal(shape=[3,1],stddev=1,seed=1))

x=tf.placeholder(dtype=tf.float32,shape=(1,2),name='input')

a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    print(sess.run(y,feed_dict={x:[[0.7,0.9]]}))

[[3.957578]]


In [39]:
#forward propogation batch

import tensorflow as tf

w1=tf.Variable(tf.random_normal(shape=[2,3],stddev=1,seed=1))
w2=tf.Variable(tf.random_normal(shape=[3,1],stddev=1,seed=1))

x=tf.placeholder(dtype=tf.float32,shape=(3,2),name='input')#batch

a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    print(sess.run(y,feed_dict={x:[[0.7,0.9],[0.5,0.9],[0.7,0.5]]}))

[[3.957578 ]
 [3.3842702]
 [3.0904665]]


In [41]:
# coss function
'''
cross_entropy = -tf.reduce_mean(y_*tf.log(tf.clip_by_value(y,1e-10,1.0)))

learning_rate = 0.001

train_step = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cross_entropy)
'''

'\ncross_entropy = -tf.reduce_mean(y_*tf.log(tf.clip_by_value(y,1e-10,1.0)))\n\nlearning_rate = 0.001\n\ntrain_step = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cross_entropy)\n'

In [42]:
from numpy.random import RandomState

In [64]:
rdm=RandomState(1)

In [65]:
X=rdm.rand(5,2)

In [66]:
Y=[[int(x1+x2<1)] for (x1,x2) in X]

In [67]:
Y

[[0], [1], [1], [1], [1]]

In [58]:
X

array([[0.4173048 , 0.55868983],
       [0.14038694, 0.19810149],
       [0.80074457, 0.96826158],
       [0.31342418, 0.69232262],
       [0.87638915, 0.89460666]])

In [76]:
# binary-classification with nn
import tensorflow as tf

from numpy.random import RandomState

batch_size=8
dataset_size=128
STEPS=5000

#define layers
w1=tf.Variable(tf.random_normal(shape=[2,3],seed=1,stddev=1))
w2=tf.Variable(tf.random_normal(shape=[3,1],seed=1,stddev=1))

#define input
x=tf.placeholder(tf.float32,shape=(None,2),name='x-input')
y_=tf.placeholder(tf.float32,shape=(None,1),name='y-input')

#generate random dataset
rdm=RandomState(seed=2)
X=rdm.rand(dataset_size,2)

'''
rule:x1+x2<1,y=0 ; x1+x2>1,y=1
'''
Y=[[int(x1+x2<1)] for (x1,x2) in X]


#define forward-propogation
a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

#define coss function
cross_entropy=-tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y,1e-10,1.0)))

#define backforward-propogation
learning_rate=0.001
train_step=tf.train.AdadeltaOptimizer(learning_rate).minimize(cross_entropy)


#create session and train
with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    
    print(sess.run(w1))
    print(sess.run(w2))
    
    '''
    [[-0.8113182   1.4845988   0.06532937]
     [-2.4427042   0.0992484   0.5912243 ]]
    [[-0.8113182 ]
     [ 1.4845988 ]
     [ 0.06532937]]
    '''
    
    for i in range(STEPS):
        start=(i*batch_size)%dataset_size
        end=min(start+batch_size,data_size)
        
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
        
        if i % 1000 == 0:
            total_cross_entropy=sess.run(cross_entropy,feed_dict={x:X,y_:Y})
            print('After %d trainning step(s),cross_entropy on all data is %g'%(i,total_cross_entropy))
            
            '''
            After 0 trainning step(s),cross_entropy on all data is 0.0677412
            After 1000 trainning step(s),cross_entropy on all data is 0.0677362
            After 2000 trainning step(s),cross_entropy on all data is 0.0677311
            After 3000 trainning step(s),cross_entropy on all data is 0.0677259
            After 4000 trainning step(s),cross_entropy on all data is 0.0677207
            '''
            
    print(sess.run(w1))
    print(sess.run(w2))
    
    '''
    [[-0.81146723  1.4846718   0.0654671 ]
     [-2.4427042   0.0993684   0.5913538 ]]
    [[-0.81144786]
     [ 1.484672  ]
     [ 0.06545771]]
    '''

[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
After 0 trainning step(s),cross_entropy on all data is 0.0677411
After 1000 trainning step(s),cross_entropy on all data is 0.0676783
After 2000 trainning step(s),cross_entropy on all data is 0.0676121
After 3000 trainning step(s),cross_entropy on all data is 0.067546
After 4000 trainning step(s),cross_entropy on all data is 0.0674799
[[-0.81270415  1.485931    0.06668379]
 [-2.443958    0.10045876  0.5924246 ]]
[[-0.8126457 ]
 [ 1.4860655 ]
 [ 0.06659038]]
